<?php
// Include the database connection
include '../dbconnection.php';

// Check if the form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Get form data
    $usertype_id = $_POST['usertype_id'];
    $username = $_POST['username'];
    $password = password_hash($_POST['password'], PASSWORD_BCRYPT);

    // Generate or fetch unique_code from the database
    // Assuming it's generated by a trigger or default value in the database
    // No need to set it explicitly here

    // Prepare and bind
    $stmt = $conn->prepare("INSERT INTO users (usertype_id, username, password) VALUES (?, ?, ?)");
    $stmt->bind_param("iss", $usertype_id, $username, $password);

    // Execute the statement
    try {
        $stmt->execute();
        echo "New record created successfully";
    } catch (mysqli_sql_exception $e) {
        echo "Error: " . $e->getMessage();
    }

    // Close the statement
    $stmt->close();
}

// Close the connection
$conn->close();
?>
